version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imd-seat-be
    ports:
      - "8080:8080"
    volumes:
      - ./etc/config.yaml:/app/etc/config.yaml
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: seat_database
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped


volumes:
  mysql_data:
