# EXAMPLE
Name: "seat-service"
Host: "0.0.0.0"
Port: 8080
  
MySQL:
  Name: "test"         
  User: "root"                  
  Password: "beky2006"         
  Host: "localhost"             
  Port: 3306                    

Auth:
  AccessSecret: "abcdefghijklmn12345"  # JWT 密钥
  AccessExpire: 3600                # JWT Token 过期时间（单位：秒）
